const projects = [
    {
        id: 1,
        projectName: "Personal",
        todos: [
            {
                id: 1,
                title: "Buy groceries",
                description: "Milk, Bread, Eggs, Butter",
                dueDate: "2025-03-16",
                priority: "High",
                tags: ["shopping", "urgent"],
                notes: "Check for discounts on dairy products.",
                isCompleted: false,
            },
            {
                id: 2,
                title: "Clean the house",
                description: "Vacuum, Dust, Mop",
                dueDate: "2025-03-12",
                priority: "Medium",
                tags: ["chores"],
                notes: "Focus on the living room and kitchen.",
                isCompleted: true,
            },
            {
                id: 3,
                title: "Read a book",
                description: "Finish reading 'The Great Gatsby'",
                dueDate: "2025-03-15",
                priority: "Low",
                tags: ["leisure"],
                notes: "Read at least one chapter per day.",
                isCompleted: false,
            },
        ],
    },
    {
        id: 2,
        projectName: "Work",
        todos: [
            {
                id: 4,
                title: "Finish report",
                description: "Complete the quarterly financial report",
                dueDate: "2025-04-09",
                priority: "High",
                tags: ["work", "urgent"],
                notes: "Include the latest sales data.",
                isCompleted: true,
            },
            {
                id: 5,
                title: "Team meeting",
                description: "Discuss project milestones",
                dueDate: "2025-03-11",
                priority: "Medium",
                tags: ["meeting"],
                notes: "Prepare the presentation slides.",
                isCompleted: false,
            },
            {
                id: 6,
                title: "Code review",
                description: "Review code for the new feature",
                dueDate: "2025-03-13",
                priority: "Low",
                tags: ["development"],
                notes: "Focus on the authentication module.",
                isCompleted: false,
            },
        ],
    },
    {
        id: 3,
        projectName: "Fitness",
        todos: [
            {
                id: 7,
                title: "Morning run",
                description: "Run 5 kilometers",
                dueDate: "2025-03-15",
                priority: "High",
                tags: ["exercise"],
                notes: "Try to maintain a steady pace.",
                isCompleted: true,
            },
            {
                id: 8,
                title: "Yoga session",
                description: "Attend online yoga class",
                dueDate: "2025-03-15",
                priority: "Medium",
                tags: ["exercise", "wellness"],
                notes: "Focus on breathing exercises.",
                isCompleted: false,
            },
            {
                id: 9,
                title: "Gym workout",
                description: "Strength training at the gym",
                dueDate: "2025-03-15",
                priority: "Low",
                tags: ["exercise"],
                notes: "Include both upper and lower body exercises.",
                isCompleted: false,
            },
        ],
    },
];

export default projects;
